### PR TITLE
Add prod support to cirq device

### PR DESCRIPTION
**Pull request by astralcai**
Add support for Prod observable.

[sc-60542]

### CODE REVIEW

**Comment by Alex-Preciado** [comment]
Relevant Shortcut Stories: [sc-60542]

**Review by Qottmann — APPROVED** [review]

**Comment by Qottmann** [comment]
can you retrigger and if it still gets stuck get someone with the power to overwrite it? Next one in line for demo blockers 🙃

**Comment by Qottmann** [comment]
@Alex-Preciado could you overwrite the codecov requirement and merge this? This is currently blocking the work on fixing demos

**Comment by Alex-Preciado** [comment]
Hey @Qottmann, we noticed that the Codecov Token was missing in this repository. I've added it now to this repository's secrets. I'm merging @astralcai 's changes now with a green CI status. You should now be unblocked 😎

**Comment by Qottmann** [comment]
Thanks so much 🙌

**Pull request merged**
