### PR TITLE
Analytic fix

### PR DESCRIPTION
**Pull request by Thenerdstation**
Fixes to account for the removal of the `analytic` keyword.

### CODE REVIEW

**Review by josh146 — APPROVED** [review]
Thanks @Thenerdstation 💯 

Does this close #53, or is that still open to some degree? iirc, maybe that is no longer an issue, since we returned to the manual approach of computing expvals for samples always, rather than asking Cirq for the expval directly.

Perhaps now we can start to add that back in.

**Comment by Thenerdstation** [comment]
I would consider it still open, as this PR doesn't add the `simulate_expectation_values` method from Cirq.

**Comment by Thenerdstation** [comment]
Should I merge with the git link in the requirements?

**Comment by josh146** [comment]
yep go for it

**Pull request merged**
